export const question = [
  {
    id: 1,
    question:
      "What is the recommended percentage of your income to save each month for emergencies and unexpected expenses?",
    src: "/images/q1.jpg",
    choices: ["10-15%", "20-25%", "5-10%", "30-35%"],
    correct: "5-10%",
  },
  {
    id: 2,
    question: "What is a good way to manage credit card debt?",
    src: "/images/q2.jpg",
    choices: [
      "Paying more than minimum payment each month",
      "Using balance transfer credit cards",
      "Paying off the highest interest rate card first",
      "Using cash advances to pay off debt",
    ],
    correct: "Paying more than minimum payment each month",
  },
  {
    id: 3,
    question:
      "True or False: It's a good idea to have a mix of different types of credit accounts, such as credit cards, loans, and mortgages.",
    src: "/images/q3.jpg",
    choices: ["True", "False"],
    correct: "False",
  },
  {
    id: 4,
    question: "What is the 50/30/20 rule when it comes to budgeting?",
    src: "/images/q4.jpg",
    choices: [
      "Housing, Saving, and expenses",
      "Necessity, wants and saving",
      "Food, housing and transportation",
      "Debt repayment, investements and spending",
      ,
    ],
    correct: "Necessity, wants and saving",
  },
  {
    id: 5,
    question: "What is the first step in creating a budget?",
    src: "/images/q2.jpg",
    choices: [
      "Setting financial goals",
      "Tracking expenses",
      "Determining your net worth",
      "Creating a debt repayment plan",
    ],
    correct: "Tracking expenses",
  },
  {
    id: 6,
    question: "What is the best way to invest in stocks for long-term growth?",
    src: "/images/q1.jpg",
    choices: [
      "Investing in individual stocks",
      "Buying mutual funds",
      "Trading options",
      "Investing in real estate",
    ],
    correct: "Buying mutual funds",
  },
  {
    id: 7,
    question: "What is an emergency fund?",
    src: "/images/q3.jpg",
    choices: [
      "Money you use for unexpected expenses",
      "Money you set aside for retirement",
      "Money you invest in stocks",
      "Money you use for a down payment on a house",
    ],
    correct: "Money you use for unexpected expenses",
  },
  {
    id: 8,
    src: "/images/q1.jpg",
    question: "What is the recommended debt-to-income ratio?",
    choices: [
      "Less than 50%",
      "Less than 70%",
      "It depends on your financial situation",
      "Less than 30%",
    ],
    correct: "Less than 30%",
  },
  {
    id: 9,
    src: "/images/q2.jpg",
    question: "What is compound interest?",
    choices: [
      "Interest paid on the principal amount and any interest earned",
      "Interest paid on the principal amount",
      "Interest paid only on the interest earned",
      "Interest paid only at maturity",
    ],
    correct: "Interest paid on the principal amount and any interest earned",
  },
  {
    id: 10,
    src: "/images/q3.jpg",
    question: "What is a Roth IRA?",
    choices: [
      "A retirement account with tax-deductible contributions",
      "A retirement account with tax-free withdrawals",
      "A type of insurance policy",
      "A type of mutual fund",
    ],
    correct: "A retirement account with tax-free withdrawals",
  },
  {
    id: 11,
    src: "/images/q4.jpg",
    question: "What is a 401(k)?",
    choices: [
      "A savings account",
      "A type of bond",
      "A retirement account offered by employers",
      "A type of stock",
    ],
    correct: "A retirement account offered by employers",
  },
  {
    id: 12,
    src: "/images/q1.jpg",
    question: "What is the difference between a stock and a bond?",
    choices: [
      "Stocks are issued by companies, while bonds are issued by governments",
      "Stocks represent ownership in a company, while bonds represent debt owed by a company or government",
      "Stocks are always riskier than bonds",
      "Bonds are always riskier than stocks",
    ],
    correct:
      "Stocks represent ownership in a company, while bonds represent debt owed by a company or government",
  },
  {
    id: 13,
    src: "/images/q2.jpg",
    question: "What is a credit report?",
    choices: [
      "A document that shows your credit history and creditworthiness",
      "A document that shows your income and expenses",
      "A document that shows your tax returns",
      " A document that shows your investment portfolio",
    ],
    correct: "A document that shows your credit history and creditworthiness",
  },
  {
    id: 14,
    src: "/images/q3.jpg",
    question: "What is a budget deficit?",
    choices: [
      "When you save more money than you spend",
      "When you have no money left at the end of the month",
      "When your income is higher than your expenses",
      "When you spend more money than you make",
    ],
    correct: "When you spend more money than you make",
  },
  {
    id: 15,
    src: "/images/q4.jpg",
    question: "What is a secured loan?",
    choices: [
      "A loan that requires collateral",
      "A loan that does not require collateral",
      "A loan with a low interest rate",
      "A loan with a high interest rate",
    ],
    correct: "A loan that requires collateral",
  },
  {
    id: 16,
    src: "/images/q1.jpg",
    question: "What is diversification?",
    choices: [
      "Spreading your investments across different assets to reduce risk",
      "Investing all your money in one stock",
      "Investing all your money in one industry",
      "Investing all your money in one asset class",
    ],
    correct:
      "Spreading your investments across different assets to reduce risk",
  },
  {
    id: 17,
    src: "/images/q2.jpg",
    question: "What is a credit utilization ratio?",
    choices: [
      "The percentage of your income that you are using to pay off debt",
      "The percentage of your income that you are saving",
      "The percentage of your available credit that you are using",
      "The percentage of your income that you are spending on needs",
    ],
    correct: "The percentage of your available credit that you are using",
  },
  {
    id: 18,
    src: "/images/q3.jpg",
    question: "What is a debt-to-income ratio?",
    choices: [
      "The percentage of your income that goes towards savings",
      "The percentage of your income that goes towards debt payments",
      "The percentage of your income that goes towards taxes",
      "The percentage of your income that goes towards discretionary spending",
    ],
    correct: "The percentage of your income that goes towards debt payments",
  },
  {
    id: 19,
    src: "/images/q4.jpg",
    question: "What is an HSA?",
    choices: [
      "A retirement savings account that allows you to save money tax-free",
      "A savings account that allows you to earn high interest rates",
      "A credit card that can only be used to pay for medical expenses",
      "A health savings account that allows you to save money tax-free to pay for medical expenses",
    ],
    correct:
      "A health savings account that allows you to save money tax-free to pay for medical expenses",
  },
  {
    id: 20,
    src: "/images/q2.jpg",
    question: "What is the difference between a stock and a bond?",
    choices: [
      "Stocks represent ownership in a company, while bonds represent a loan made to a company",
      "Stocks represent a loan made to a company, while bonds represent ownership in a company",
      "Stocks and bonds are the same thing",
      "Stocks represent ownership in a government, while bonds represent ownership in a company",
    ],
    correct:
      "Stocks represent ownership in a company, while bonds represent a loan made to a company",
  },
];
